# Generated by Django 4.1.7 on 2023-04-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_blog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='default', max_length=255, null=True),
        ),
    ]
