# Generated by Django 4.1.7 on 2023-04-23 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_user_comment_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
    ]
